server:
  port: 8081
  servlet:
    session:
      timeout: 1800s
      cookie:
        secure: true


spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
  type-enums-package: cn.porsche.*.*.enums
  default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)